/**
 * awareness.ts — Localized health-awareness cards for rural and low-literacy communities.
 *
 * Each card is written in plain, accessible language and designed for audio read-aloud via TTS.
 * Offline-first: static and bundled into the client build.
 */

export interface HealthLiteracyCard {
  id: string;
  icon: string;
  titleEn: string;
  titleHi: string;
  category: "child" | "maternal" | "nutrition" | "fever" | "firstaid" | "chronic";
  summaryEn: string;
  summaryHi: string;
  pointsEn: string[];
  pointsHi: string[];
  whenToReferEn: string;
  whenToReferHi: string;
}

export const HEALTH_AWARENESS_CARDS: HealthLiteracyCard[] = [
  {
    id: "card-child-danger",
    icon: "👶",
    category: "child",
    titleEn: "Recognizing Child Danger Signs",
    titleHi: "बच्चों में गंभीर खतरे के संकेत पहचानें",
    summaryEn: "Young children can deteriorate quickly. Check for chest indrawing, lethargy, and inability to feed.",
    summaryHi: "छोटे बच्चों की तबीयत तेज़ी से बिगड़ सकती है। पसली चलना, सुस्ती और दूध न पीना गंभीर खतरे की निशानी हैं।",
    pointsEn: [
      "Cannot drink or breastfeed at all.",
      "Vomits everything taken.",
      "Fast breathing or lower chest sucking inward (chest indrawing).",
      "Abnormally sleepy, limp, or unresponsive.",
      "Convulsions (fits) or abnormal jerking.",
    ],
    pointsHi: [
      "बच्चा माँ का दूध या पानी बिल्कुल न पी पाए।",
      "जो भी पिए या खाए, तुरंत उल्टी कर दे।",
      "साँस बहुत तेज़ चले या साँस लेते समय सीना अंदर धंसे (पसली चलना)।",
      "बहुत सुस्त हो, जगाने पर भी आँख न खोले या बेसुध रहे।",
      "शरीर में झटके (दौरा) आएँ।",
    ],
    whenToReferEn: "If ANY of these signs are present, take the child to the PHC or hospital IMMEDIATELY without waiting.",
    whenToReferHi: "इनमें से कोई भी एक लक्षण दिखने पर बिना देर किए तुरंत अस्पताल या पीएचसी ले जाएँ।",
  },
  {
    id: "card-maternal-danger",
    icon: "🤰",
    category: "maternal",
    titleEn: "Maternal Care & Warning Signs",
    titleHi: "गर्भावस्था में खतरे के संकेत",
    summaryEn: "Every pregnant mother must recognize early complications that need emergency hospital care.",
    summaryHi: "गर्भवती महिला और परिवार को उन लक्षणों की जानकारी होनी चाहिए जिनमें तुरंत अस्पताल पहुँचना ज़रूरी है।",
    pointsEn: [
      "Any vaginal bleeding or spotting during pregnancy.",
      "Severe persistent headache, blurred vision, or swelling in face and hands (signs of high BP).",
      "High fever with shivering.",
      "Water breaking before labor pains start.",
      "Reduced or absent baby movements in late pregnancy.",
    ],
    pointsHi: [
      "गर्भावस्था में किसी भी समय रक्तस्राव (खून जाना)।",
      "तेज़ सिरदर्द, आँखों के आगे धुंधलापन या चेहरे व हाथों पर अचानक सूजन आना (उच्च रक्तचाप का संकेत)।",
      "कंपकंपी के साथ तेज़ बुखार।",
      "प्रसव पीड़ा शुरू होने से पहले ही पानी की थैली फटना।",
      "गर्भ में शिशु की हलचल कम होना या बंद महसूस होना।",
    ],
    whenToReferEn: "Do not wait for scheduled delivery date if bleeding, high BP signs, or sudden pain appear.",
    whenToReferHi: "खून बहने, तेज़ सिरदर्द या असहनीय पेट दर्द होने पर प्रसव की तारीख का इंतज़ार न करें, तुरंत एम्बुलेंस बुलाएँ।",
  },
  {
    id: "card-anemia-nutrition",
    icon: "🥗",
    category: "nutrition",
    titleEn: "Anemia Prevention & Healthy Blood",
    titleHi: "खून की कमी (एनीमिया) से बचाव और पौष्टिक आहार",
    summaryEn: "Low hemoglobin makes mothers and children weak and tired. Iron-rich foods and IFA tablets restore strength.",
    summaryHi: "हीमोग्लोबिन कम होने से शरीर में कमजोरी, सांस फूलना और थकान रहती है। सही खान-पान और आयरन की गोली से खून बढ़ता है।",
    pointsEn: [
      "Eat green leafy vegetables (spinach, fenugreek, bathua, drumstick leaves) daily.",
      "Include jaggery (gud), roasted chana, sesame (til), and sprouted pulses in meals.",
      "Take Iron-Folic Acid (IFA) tablets after food, with lemon water or amla (Vitamin C helps absorption).",
      "Avoid drinking tea or coffee within 1 hour of taking iron tablets or food.",
      "Deworm with Albendazole every 6 months under health worker supervision.",
    ],
    pointsHi: [
      "रोज़ाना हरी पत्तेदार सब्ज़ियाँ (पालक, मेथी, बथुआ, सहजन के पत्ते) खाएँ।",
      "गुड़, भुना चना, तिल और अंकुरित दालों को भोजन में शामिल करें।",
      "आयरन की नीली/लाल गोली खाना खाने के बाद नींबू पानी या आँवला के साथ लें (विटामिन-सी से आयरन शरीर में सोखता है)।",
      "दवा या खाने के 1 घंटे पहले और बाद तक चाय-कॉफ़ी बिल्कुल न पिएँ।",
      "पेट के कीड़े मारने की दवा (एल्बेंडाजोल) हर 6 महीने में आशा दीदी की सलाह से लें।",
    ],
    whenToReferEn: "If severe breathlessness on walking, extreme pale tongue/eyes, or swollen ankles occur, check Hb at PHC.",
    whenToReferHi: "चलने पर अत्यधिक साँस फूलना, जीभ या पलकें बिल्कुल सफेद दिखना गंभीर एनीमिया का लक्षण है — तुरंत जाँच कराएँ।",
  },
  {
    id: "card-ors-diarrhea",
    icon: "💧",
    category: "firstaid",
    titleEn: "ORS & Diarrhea Hydration at Home",
    titleHi: "दस्त में ओआरएस घोल और पानी की कमी से बचाव",
    summaryEn: "Diarrhea kills by dehydration, not the loose stools themselves. Replacing lost fluids immediately saves lives.",
    summaryHi: "दस्त में मौत दस्त से नहीं बल्कि शरीर में पानी और नमक सूखने से होती है। तुरंत ओआरएस देना जीवन बचाता है।",
    pointsEn: [
      "Mix 1 full packet of ORS in 1 litre of clean drinking water. Do not add sugar or boil it after mixing.",
      "Give ORS after EVERY loose motion: half cup for small babies, 1 full cup for older children.",
      "Give Zinc tablets once daily for 14 days — this repairs intestines and prevents future diarrhea.",
      "Keep feeding normally; continued breastfeeding is essential.",
      "If ORS is unavailable, give rice kanji with salt, coconut water, or clean dal water.",
    ],
    pointsHi: [
      "ओआरएस का पूरा पैकेट 1 लीटर साफ पीने के पानी में घोलें। इसमें अलग से चीनी या नमक न मिलाएँ।",
      "हर बार पतले दस्त के बाद ओआरएस घोल पिलाएँ: छोटे बच्चे को आधा कप, बड़े बच्चे को पूरा कप।",
      "जिंक की गोली 14 दिनों तक लगातार दें — इससे आंतें मज़बूत होती हैं और आगे दस्त नहीं होते।",
      "खाना-पीना बंद न करें; माँ का दूध लगातार पिलाते रहें।",
      "ओआरएस न होने पर चावल का माँड़ (नमक मिलाकर), नारियल पानी या पतली दाल का पानी दें।",
    ],
    whenToReferEn: "Take to PHC if: sunken eyes, skin pinch stays pinched, blood in stool, or cannot drink.",
    whenToReferHi: "आँखें अंदर धंसना, पेट की चमड़ी खींचने पर धीरे-धीरे वापस जाना, या मल में खून आना गंभीर खतरे की घंटी है।",
  },
  {
    id: "card-home-fever",
    icon: "🌡️",
    category: "fever",
    titleEn: "Fever Management at Home",
    titleHi: "घर पर बुखार की सही देखभाल",
    summaryEn: "Fever is the body's way of fighting infection. Keep the patient comfortable and hydrated, avoiding harmful practices.",
    summaryHi: "बुखार शरीर द्वारा बीमारी से लड़ने का संकेत है। मरीज़ को ठंडा व हवादार रखें और गलत दवाओं से बचें।",
    pointsEn: [
      "Wipe body with a cloth soaked in normal tap water (tepid sponging). NEVER use ice water or alcohol.",
      "Dress in light cotton clothes; do not wrap tightly in heavy blankets.",
      "Give plenty of fluids: water, ORS, thin soup, and fruit juices.",
      "Use paracetamol in the correct dose according to weight or health worker advice.",
      "NEVER give aspirin to children or teenagers with fever.",
    ],
    pointsHi: [
      "सामान्य नल के पानी में कपड़ा भिगोकर पूरे शरीर पर पट्टी करें। बर्फ का पानी कभी न इस्तेमाल करें।",
      "हल्के सूती कपड़े पहनाएँ; भारी रजाई या कंबल में न लपेटें।",
      "खूब पानी, छाछ, दाल का पानी और तरल आहार दें ताकि डिहाइड्रेशन न हो।",
      "स्वास्थ्य कार्यकर्ता की बताई खुराक के अनुसार केवल पैरासिटामोल दें।",
      "बच्चों को बुखार में कभी भी एस्पिरिन या ब्रूफेन (Ibuprofen) न दें।",
    ],
    whenToReferEn: "Go to the PHC if fever lasts over 3 days, crosses 103°F (39.5°C), or has rash/stiff neck.",
    whenToReferHi: "यदि बुखार 3 दिन से अधिक रहे, शरीर पर दाने निकलें या गर्दन अकड़ जाए तो तुरंत डॉक्टर को दिखाएँ।",
  },
  {
    id: "card-hand-hygiene",
    icon: "🧼",
    category: "firstaid",
    titleEn: "Handwashing & Safe Drinking Water",
    titleHi: "हाथों की धुलाई और सुरक्षित पेयजल",
    summaryEn: "Washing hands with soap at critical times prevents over 40% of childhood diarrhea and pneumonia.",
    summaryHi: "साबुन से हाथ धोने की सही आदत बच्चों को उल्टी-दस्त और निमोनिया जैसी जानलेवा बीमारियों से बचाती है।",
    pointsEn: [
      "Always wash with soap: after toilet, after cleaning baby's bottom, before cooking, and before eating.",
      "Rub palms, backs of hands, between fingers, and under nails for at least 20 seconds.",
      "Keep drinking water in clean, narrow-mouthed vessels with tight lids.",
      "Use a long-handled ladle (dolu) to draw water — never dip hands into storage pots.",
      "Boil water or add chlorine tablets during monsoon or following pipeline repairs.",
    ],
    pointsHi: [
      "साबुन से हाथ अवश्य धोएँ: शौच के बाद, बच्चे का मल साफ करने के बाद, खाना बनाने और खाने से पहले।",
      "हथेलियों, उँगलियों के बीच और नाखूनों को कम से कम 20 सेकंड तक अच्छी तरह रगड़ें।",
      "पीने का पानी हमेशा साफ़, ढकने वाले बर्तन में रखें।",
      "पानी निकालने के लिए डंडी वाले लोटे का इस्तेमाल करें — मटके में हाथ कभी न डुबोएँ।",
      "बरसात के मौसम में पानी उबालकर या छानकर पिएँ।",
    ],
    whenToReferEn: "If several family members develop sudden watery diarrhea, inform your local ASHA immediately.",
    whenToReferHi: "गाँव या घर में एक साथ कई लोगों को उल्टी-दस्त हो तो तुरंत आशा या एएनएम दीदी को सूचित करें।",
  },
  {
    id: "card-when-to-phc",
    icon: "🏥",
    category: "firstaid",
    titleEn: "When to Go to the PHC Immediately",
    titleHi: "प्राथमिक स्वास्थ्य केंद्र (PHC) कब तुरंत जाएँ",
    summaryEn: "Do not delay for a doctor's weekly visit if acute emergency signs appear. Rural primary centers are open 24/7 for stabilization.",
    summaryHi: "गंभीर लक्षणों में झोलाछाप या हफ्ते के डॉक्टर का इंतजार न करें। आपात स्थिति में तुरंत सरकारी केंद्र पहुँचें।",
    pointsEn: [
      "Sudden heavy chest pressure or pain radiating to jaw or left arm.",
      "Difficulty breathing or blue lips/fingers.",
      "Sudden weakness or numbness on one side of the face or body (stroke sign).",
      "Persistent vomiting with inability to keep any fluids down.",
      "Uncontrolled bleeding from any wound or after childbirth.",
      "High fever with confusion, delirium, or unable to recognize family members.",
    ],
    pointsHi: [
      "सीने में अचानक भारी दबाव, जकड़न या दर्द जो बाएँ हाथ या जबड़े तक फैले।",
      "साँस लेने में गंभीर तकलीफ़ या होंठ व नाखून नीले पड़ना।",
      "चेहरे या शरीर के एक तरफ अचानक कमजोरी या सुन्नपन (लकवे का लक्षण)।",
      "लगातार उल्टी होना और पानी की एक घूँट भी पेट में न रुकना।",
      "चोट लगने या प्रसव के बाद खून का बहाव न रुकना।",
      "तेज़ बुखार के साथ बड़बड़ाना या परिजनों को न पहचान पाना।",
    ],
    whenToReferEn: "Use the 108/104 free ambulance service for emergency transport to the nearest CHC/PHC.",
    whenToReferHi: "आपातकालीन एम्बुलेंस के लिए निःशुल्क 108 या 104 नंबर डायल करें।",
  },
  {
    id: "card-bp-heart",
    icon: "🫀",
    category: "chronic",
    titleEn: "Blood Pressure & Heart Health",
    titleHi: "उच्च रक्तचाप (हाई बीपी) और दिल की सुरक्षा",
    summaryEn: "High blood pressure has no obvious symptoms early on (the silent condition). Regular checks and less salt prevent paralysis and heart attacks.",
    summaryHi: "उच्च रक्तचाप का शुरुआती दौर में कोई लक्षण नहीं दिखता। नियमित बीपी नपवाने और कम नमक से दिल का दौरा और लकवा रुकता है।",
    pointsEn: [
      "Get your blood pressure checked at least once every 6 months if over 30.",
      "Reduce salt in food: avoid extra raw salt on salads, papad, pickles (achaar), and namkeen.",
      "Walk briskly for 30 minutes daily; maintain healthy body weight.",
      "Never stop prescribed BP medicines even when feeling completely healthy.",
      "Avoid smoking, bidi, gutkha, and excessive alcohol.",
    ],
    pointsHi: [
      "30 वर्ष की आयु के बाद हर 6 महीने में कम से कम एक बार बीपी ज़रूर नपवाएँ।",
      "भोजन में नमक कम करें: ऊपर से कच्चा नमक, पापड़, अचार और नमकीन का सेवन सीमित करें।",
      "रोज़ाना 30 मिनट तेज़ पैदल चलें और वजन नियंत्रित रखें।",
      "बीपी की डॉक्टर द्वारा लिखी दवा कभी भी खुद से बंद न करें, चाहे आप पूरी तरह स्वस्थ महसूस कर रहे हों।",
      "बीड़ी, सिगरेट, गुटखा और तंबाकू से पूर्ण परहेज़ करें।",
    ],
    whenToReferEn: "If BP is over 160/100 or accompanied by severe headache or chest tightness, visit PHC today.",
    whenToReferHi: "यदि बीपी 160/100 से अधिक आए या सीने में भारीपन लगे तो उसी दिन सरकारी अस्पताल में जाँच कराएँ।",
  },
  {
    id: "card-respiratory-smoke",
    icon: "🫁",
    category: "chronic",
    titleEn: "Clean Air & Lung Protection",
    titleHi: "साँस की सुरक्षा और धुआँ रहित वातावरण",
    summaryEn: "Chulha smoke inside closed rooms damages lungs as much as smoking cigarettes, especially in mothers and babies.",
    summaryHi: "कमरे के अंदर चूल्हे का धुआँ फेफड़ों को उतना ही नुकसान पहुँचाता है जितना बीड़ी पीना। महिलाओं और बच्चों में दमा बढ़ाता है।",
    pointsEn: [
      "Cook in a well-ventilated area with a chimney or open window.",
      "Switch to PM Ujjwala LPG gas cooking whenever possible.",
      "Keep infants and young children away from direct cookstove smoke.",
      "Cover nose and mouth with a wet gamcha/cloth when threshing grain or in dusty crop harvesting.",
      "If chronic cough lasts more than 2 weeks, test for Tuberculosis (TB) free at the PHC.",
    ],
    pointsHi: [
      "रसोई में खिड़की या रोशनदान खुली रखें ताकि चूल्हे का धुआँ तुरंत बाहर निकल सके।",
      "संभव हो तो उज्ज्वला गैस चूल्हे का उपयोग करें।",
      "खाना बनाते समय छोटे बच्चों को चूल्हे के धुएँ से दूर रखें।",
      "फसल कटाई या थ्रेशर के समय नाक व मुँह पर गीला गमछा बाँधें।",
      "यदि खाँसी 2 हफ्ते से ज़्यादा समय तक रहे, तो सरकारी अस्पताल में टीबी (TB) की निःशुल्क बलगम जाँच कराएँ।",
    ],
    whenToReferEn: "Cough with blood, unexplained weight loss, or evening fever warrants immediate sputum testing.",
    whenToReferHi: "खाँसी में खून आना, शाम को हल्का बुखार या तेज़ी से वजन घटना टीबी का संकेत हो सकता है — तुरंत जाँच कराएँ।",
  },
  {
    id: "card-newborn-care",
    icon: "👶",
    category: "child",
    titleEn: "Newborn Care & Exclusive Breastfeeding",
    titleHi: "नवजात शिशु की देखभाल और केवल माँ का दूध",
    summaryEn: "The first hour after birth and the first 6 months build lifelong immunity. Keep baby warm and give only breast milk.",
    summaryHi: "जन्म का पहला घंटा और शुरुआती 6 महीने बच्चे की जीवन भर की इम्युनिटी तय करते हैं। बच्चे को केवल माँ का दूध दें।",
    pointsEn: [
      "Start breastfeeding within 1 hour of birth (the thick yellow colostrum milk is baby's first vaccine).",
      "Give ONLY breast milk for the first 6 months — NO water, NO honey (ghutti), NO goat milk.",
      "Keep baby warm with skin-to-skin contact (Kangaroo Mother Care).",
      "Keep the umbilical cord stump dry and clean; do not apply cow dung, ash, or oil.",
      "Delay baby's first bath for at least 48 hours to prevent hypothermia.",
    ],
    pointsHi: [
      "जन्म के 1 घंटे के भीतर माँ का पहला गाढ़ा पीला दूध (खीस/कोलोस्ट्रम) ज़रूर पिलाएँ — यह बच्चे का पहला टीका है।",
      "पहले 6 महीने तक केवल माँ का दूध दें — पानी, घुट्टी, शहद या गाय-बकरी का दूध बिल्कुल न दें।",
      "बच्चे को माँ के सीने से लगाकर गर्म रखें (कंगारू मदर केयर)।",
      "नाल पर कुछ भी (राख, गोबर, तेल) न लगाएँ, उसे सूखा और साफ़ रखें।",
      "जन्म के कम से कम 48 घंटे बाद ही बच्चे को नहलाएँ ताकि ठंड न लगे।",
    ],
    whenToReferEn: "If baby feels cold to touch, skin looks yellow (jaundice) on day 1, or breathing fast, go to PHC.",
    whenToReferHi: "यदि नवजात शिशु छूने पर ठंडा लगे, नाल से मवाद आए या त्वचा पीली दिखे तो तुरंत अस्पताल ले जाएँ।",
  },
];
