/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PatientIdRouteImport } from './routes/patient.$id'
import { Route as PatientIdIndexRouteImport } from './routes/patient.$id.index'
import { Route as PatientIdCoughRouteImport } from './routes/patient.$id.cough'
import { Route as PatientIdScanRouteImport } from './routes/patient.$id.scan'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientIdRoute = PatientIdRouteImport.update({
  id: '/patient/$id',
  path: '/patient/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientIdIndexRoute = PatientIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatientIdRoute,
} as any)
const PatientIdCoughRoute = PatientIdCoughRouteImport.update({
  id: '/cough',
  path: '/cough',
  getParentRoute: () => PatientIdRoute,
} as any)
const PatientIdScanRoute = PatientIdScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => PatientIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/patient/$id': typeof PatientIdRouteWithChildren
  '/patient/$id/cough': typeof PatientIdCoughRoute
  '/patient/$id/scan': typeof PatientIdScanRoute
  '/patient/$id/': typeof PatientIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/patient/$id/cough': typeof PatientIdCoughRoute
  '/patient/$id/scan': typeof PatientIdScanRoute
  '/patient/$id': typeof PatientIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/patient/$id': typeof PatientIdRouteWithChildren
  '/patient/$id/cough': typeof PatientIdCoughRoute
  '/patient/$id/scan': typeof PatientIdScanRoute
  '/patient/$id/': typeof PatientIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/register'
    | '/patient/$id'
    | '/patient/$id/cough'
    | '/patient/$id/scan'
    | '/patient/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/register'
    | '/patient/$id/cough'
    | '/patient/$id/scan'
    | '/patient/$id'
  id:
    | '__root__'
    | '/'
    | '/register'
    | '/patient/$id'
    | '/patient/$id/cough'
    | '/patient/$id/scan'
    | '/patient/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RegisterRoute: typeof RegisterRoute
  PatientIdRoute: typeof PatientIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/$id': {
      id: '/patient/$id'
      path: '/patient/$id'
      fullPath: '/patient/$id'
      preLoaderRoute: typeof PatientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/$id/': {
      id: '/patient/$id/'
      path: '/'
      fullPath: '/patient/$id/'
      preLoaderRoute: typeof PatientIdIndexRouteImport
      parentRoute: typeof PatientIdRoute
    }
    '/patient/$id/cough': {
      id: '/patient/$id/cough'
      path: '/cough'
      fullPath: '/patient/$id/cough'
      preLoaderRoute: typeof PatientIdCoughRouteImport
      parentRoute: typeof PatientIdRoute
    }
    '/patient/$id/scan': {
      id: '/patient/$id/scan'
      path: '/scan'
      fullPath: '/patient/$id/scan'
      preLoaderRoute: typeof PatientIdScanRouteImport
      parentRoute: typeof PatientIdRoute
    }
  }
}

interface PatientIdRouteChildren {
  PatientIdCoughRoute: typeof PatientIdCoughRoute
  PatientIdScanRoute: typeof PatientIdScanRoute
  PatientIdIndexRoute: typeof PatientIdIndexRoute
}

const PatientIdRouteChildren: PatientIdRouteChildren = {
  PatientIdCoughRoute: PatientIdCoughRoute,
  PatientIdScanRoute: PatientIdScanRoute,
  PatientIdIndexRoute: PatientIdIndexRoute,
}

const PatientIdRouteWithChildren = PatientIdRoute._addFileChildren(
  PatientIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RegisterRoute: RegisterRoute,
  PatientIdRoute: PatientIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
