/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CrtRouteImport } from './routes/crt'
import { Route as FetRouteImport } from './routes/fet'
import { Route as FusionRouteImport } from './routes/fusion'
import { Route as ReferralRouteImport } from './routes/referral'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as Spo2RouteImport } from './routes/spo2'
import { Route as EmergencyIdRouteImport } from './routes/emergency.$id'
import { Route as PatientIdRouteImport } from './routes/patient.$id'
import { Route as PatientIdIndexRouteImport } from './routes/patient.$id.index'
import { Route as PatientIdCoughRouteImport } from './routes/patient.$id.cough'
import { Route as PatientIdGestureRouteImport } from './routes/patient.$id.gesture'
import { Route as PatientIdScanRouteImport } from './routes/patient.$id.scan'
import { Route as PatientIdSpo2RouteImport } from './routes/patient.$id.spo2'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrtRoute = CrtRouteImport.update({
  id: '/crt',
  path: '/crt',
  getParentRoute: () => rootRouteImport,
} as any)
const FetRoute = FetRouteImport.update({
  id: '/fet',
  path: '/fet',
  getParentRoute: () => rootRouteImport,
} as any)
const FusionRoute = FusionRouteImport.update({
  id: '/fusion',
  path: '/fusion',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralRoute = ReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const Spo2Route = Spo2RouteImport.update({
  id: '/spo2',
  path: '/spo2',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyIdRoute = EmergencyIdRouteImport.update({
  id: '/emergency/$id',
  path: '/emergency/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientIdRoute = PatientIdRouteImport.update({
  id: '/patient/$id',
  path: '/patient/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientIdIndexRoute = PatientIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatientIdRoute,
} as any)
const PatientIdCoughRoute = PatientIdCoughRouteImport.update({
  id: '/cough',
  path: '/cough',
  getParentRoute: () => PatientIdRoute,
} as any)
const PatientIdGestureRoute = PatientIdGestureRouteImport.update({
  id: '/gesture',
  path: '/gesture',
  getParentRoute: () => PatientIdRoute,
} as any)
const PatientIdScanRoute = PatientIdScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => PatientIdRoute,
} as any)
const PatientIdSpo2Route = PatientIdSpo2RouteImport.update({
  id: '/spo2',
  path: '/spo2',
  getParentRoute: () => PatientIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/crt': typeof CrtRoute
  '/fet': typeof FetRoute
  '/fusion': typeof FusionRoute
  '/referral': typeof ReferralRoute
  '/register': typeof RegisterRoute
  '/scan': typeof ScanRoute
  '/spo2': typeof Spo2Route
  '/emergency/$id': typeof EmergencyIdRoute
  '/patient/$id': typeof PatientIdRouteWithChildren
  '/patient/$id/cough': typeof PatientIdCoughRoute
  '/patient/$id/gesture': typeof PatientIdGestureRoute
  '/patient/$id/scan': typeof PatientIdScanRoute
  '/patient/$id/spo2': typeof PatientIdSpo2Route
  '/patient/$id/': typeof PatientIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/crt': typeof CrtRoute
  '/fet': typeof FetRoute
  '/fusion': typeof FusionRoute
  '/referral': typeof ReferralRoute
  '/register': typeof RegisterRoute
  '/scan': typeof ScanRoute
  '/spo2': typeof Spo2Route
  '/emergency/$id': typeof EmergencyIdRoute
  '/patient/$id/cough': typeof PatientIdCoughRoute
  '/patient/$id/gesture': typeof PatientIdGestureRoute
  '/patient/$id/scan': typeof PatientIdScanRoute
  '/patient/$id/spo2': typeof PatientIdSpo2Route
  '/patient/$id': typeof PatientIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/crt': typeof CrtRoute
  '/fet': typeof FetRoute
  '/fusion': typeof FusionRoute
  '/referral': typeof ReferralRoute
  '/register': typeof RegisterRoute
  '/scan': typeof ScanRoute
  '/spo2': typeof Spo2Route
  '/emergency/$id': typeof EmergencyIdRoute
  '/patient/$id': typeof PatientIdRouteWithChildren
  '/patient/$id/cough': typeof PatientIdCoughRoute
  '/patient/$id/gesture': typeof PatientIdGestureRoute
  '/patient/$id/scan': typeof PatientIdScanRoute
  '/patient/$id/spo2': typeof PatientIdSpo2Route
  '/patient/$id/': typeof PatientIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/crt'
    | '/fet'
    | '/fusion'
    | '/referral'
    | '/register'
    | '/scan'
    | '/spo2'
    | '/emergency/$id'
    | '/patient/$id'
    | '/patient/$id/cough'
    | '/patient/$id/gesture'
    | '/patient/$id/scan'
    | '/patient/$id/spo2'
    | '/patient/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/crt'
    | '/fet'
    | '/fusion'
    | '/referral'
    | '/register'
    | '/scan'
    | '/spo2'
    | '/emergency/$id'
    | '/patient/$id/cough'
    | '/patient/$id/gesture'
    | '/patient/$id/scan'
    | '/patient/$id/spo2'
    | '/patient/$id'
  id:
    | '__root__'
    | '/'
    | '/crt'
    | '/fet'
    | '/fusion'
    | '/referral'
    | '/register'
    | '/scan'
    | '/spo2'
    | '/emergency/$id'
    | '/patient/$id'
    | '/patient/$id/cough'
    | '/patient/$id/gesture'
    | '/patient/$id/scan'
    | '/patient/$id/spo2'
    | '/patient/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CrtRoute: typeof CrtRoute
  FetRoute: typeof FetRoute
  FusionRoute: typeof FusionRoute
  ReferralRoute: typeof ReferralRoute
  RegisterRoute: typeof RegisterRoute
  ScanRoute: typeof ScanRoute
  Spo2Route: typeof Spo2Route
  EmergencyIdRoute: typeof EmergencyIdRoute
  PatientIdRoute: typeof PatientIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crt': {
      id: '/crt'
      path: '/crt'
      fullPath: '/crt'
      preLoaderRoute: typeof CrtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fet': {
      id: '/fet'
      path: '/fet'
      fullPath: '/fet'
      preLoaderRoute: typeof FetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fusion': {
      id: '/fusion'
      path: '/fusion'
      fullPath: '/fusion'
      preLoaderRoute: typeof FusionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referral': {
      id: '/referral'
      path: '/referral'
      fullPath: '/referral'
      preLoaderRoute: typeof ReferralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spo2': {
      id: '/spo2'
      path: '/spo2'
      fullPath: '/spo2'
      preLoaderRoute: typeof Spo2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency/$id': {
      id: '/emergency/$id'
      path: '/emergency/$id'
      fullPath: '/emergency/$id'
      preLoaderRoute: typeof EmergencyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/$id': {
      id: '/patient/$id'
      path: '/patient/$id'
      fullPath: '/patient/$id'
      preLoaderRoute: typeof PatientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/$id/': {
      id: '/patient/$id/'
      path: '/'
      fullPath: '/patient/$id/'
      preLoaderRoute: typeof PatientIdIndexRouteImport
      parentRoute: typeof PatientIdRoute
    }
    '/patient/$id/cough': {
      id: '/patient/$id/cough'
      path: '/cough'
      fullPath: '/patient/$id/cough'
      preLoaderRoute: typeof PatientIdCoughRouteImport
      parentRoute: typeof PatientIdRoute
    }
    '/patient/$id/gesture': {
      id: '/patient/$id/gesture'
      path: '/gesture'
      fullPath: '/patient/$id/gesture'
      preLoaderRoute: typeof PatientIdGestureRouteImport
      parentRoute: typeof PatientIdRoute
    }
    '/patient/$id/scan': {
      id: '/patient/$id/scan'
      path: '/scan'
      fullPath: '/patient/$id/scan'
      preLoaderRoute: typeof PatientIdScanRouteImport
      parentRoute: typeof PatientIdRoute
    }
    '/patient/$id/spo2': {
      id: '/patient/$id/spo2'
      path: '/spo2'
      fullPath: '/patient/$id/spo2'
      preLoaderRoute: typeof PatientIdSpo2RouteImport
      parentRoute: typeof PatientIdRoute
    }
  }
}

interface PatientIdRouteChildren {
  PatientIdCoughRoute: typeof PatientIdCoughRoute
  PatientIdGestureRoute: typeof PatientIdGestureRoute
  PatientIdScanRoute: typeof PatientIdScanRoute
  PatientIdSpo2Route: typeof PatientIdSpo2Route
  PatientIdIndexRoute: typeof PatientIdIndexRoute
}

const PatientIdRouteChildren: PatientIdRouteChildren = {
  PatientIdCoughRoute: PatientIdCoughRoute,
  PatientIdGestureRoute: PatientIdGestureRoute,
  PatientIdScanRoute: PatientIdScanRoute,
  PatientIdSpo2Route: PatientIdSpo2Route,
  PatientIdIndexRoute: PatientIdIndexRoute,
}

const PatientIdRouteWithChildren = PatientIdRoute._addFileChildren(
  PatientIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CrtRoute: CrtRoute,
  FetRoute: FetRoute,
  FusionRoute: FusionRoute,
  ReferralRoute: ReferralRoute,
  RegisterRoute: RegisterRoute,
  ScanRoute: ScanRoute,
  Spo2Route: Spo2Route,
  EmergencyIdRoute: EmergencyIdRoute,
  PatientIdRoute: PatientIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
